### ISSUE TITLE
http://ticons.fokkezb.nl/ is not working

### ISSUE THREAD

**Issue by SPorwal** [FokkeZB/TiCons-Server-Arrow#9]
Hi,

I am trying to generate the icons and splash using your site but it's not working and I am getting this error. 
<img width="784" alt="screen shot 2017-01-10 at 9 10 17 am" src="https://cloud.githubusercontent.com/assets/6244008/21793086/52e0f0da-d714-11e6-9876-db48c59d0280.png">

**Comment by FokkeZB** [comment]
Ai... I accidentally deleted that 🔐 and unfortunately I don't have access to the Arrow instance anymore to change it. I'll rework the server to a plain Express app and deploy it somewhere else asap.

Thx!

**Comment by FokkeZB** [comment]
Fixed by creating a Node.js version hosted on Heroku: https://github.com/FokkeZB/TiCons-Server

Try again at http://ticons.fokkezb.nl

**Comment by SPorwal** [comment]
Thanks @FokkeZB for replying.

I think it's down again. I am getting this:

<img width="1232" alt="screen shot 2017-01-14 at 9 07 53 am" src="https://cloud.githubusercontent.com/assets/6244008/21952060/7b3ca1b0-da38-11e6-97c5-39c308be5b22.png">

**Comment by FokkeZB** [comment]
Is that after submitting the form or directly when visiting the site?

**Comment by SPorwal** [comment]
After submitting the form.

**Comment by FokkeZB** [comment]
@SPorwal could you attach the input image and the settings you are using (try if it reproduces with default settings first)?

**Comment by SPorwal** [comment]
Here is the image:

![splash_screen](https://cloud.githubusercontent.com/assets/6244008/22052234/113f43f0-dd6f-11e6-9cb1-41927c30bcda.png)

Settings: - Only Splash
In Splash tab - Unchecked Landscape, Unchecked Nine patch for Android

Tested with the default settings, getting the same results.

**Comment by FokkeZB** [comment]
Thanks. I can reproduce this indeed. I can't fix it right now, but will leave the logs here as a note for myself:

```plaintext
2017-01-21T15:47:07.396432+00:00 app[web.1]: { Error: Command failed: convert.im6: Expected 8192 bytes; found 4872 bytes `/app/tmp/89cdc95c14ddefa798f68ffa563de1af' @ warning/png.c/MagickPNGWarningHandler/1754.
2017-01-21T15:47:07.396452+00:00 app[web.1]: convert.im6: Read Exception `/app/tmp/89cdc95c14ddefa798f68ffa563de1af' @ error/png.c/MagickPNGErrorHandler/1728.
2017-01-21T15:47:07.396453+00:00 app[web.1]: convert.im6: corrupt image `/app/tmp/89cdc95c14ddefa798f68ffa563de1af' @ error/png.c/ReadPNGImage/3728.
2017-01-21T15:47:07.396454+00:00 app[web.1]: convert.im6: no images defined `/tmp/d5e616b0-dff0-11e6-bdf9-1764a7b79bbe/app/assets/iphone/Default-Portrait@2x.png' @ error/convert.c/ConvertImageCommand/3044.
2017-01-21T15:47:07.396455+00:00 app[web.1]:
2017-01-21T15:47:07.396456+00:00 app[web.1]:     at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:279:17)
2017-01-21T15:47:07.396456+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-01-21T15:47:07.396457+00:00 app[web.1]:     at ChildProcess.emit (events.js:191:7)
2017-01-21T15:47:07.396458+00:00 app[web.1]:     at maybeClose (internal/child_process.js:877:16)
2017-01-21T15:47:07.396459+00:00 app[web.1]:     at Socket.<anonymous> (internal/child_process.js:334:11)
2017-01-21T15:47:07.396460+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-01-21T15:47:07.396460+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-01-21T15:47:07.396461+00:00 app[web.1]:     at Pipe._handle.close [as _onclose] (net.js:498:12) code: 1, signal: null }
2017-01-21T15:47:11.377472+00:00 heroku[web.1]: Process running mem=1218M(237.9%)
2017-01-21T15:47:11.377472+00:00 heroku[web.1]: Error R15 (Memory quota vastly exceeded)
2017-01-21T15:47:11.377472+00:00 heroku[web.1]: Stopping process with SIGKILL
2017-01-21T15:47:11.523533+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/" host=ticons.fokkezb.nl request_id=0972e774-59d5-4f66-89d2-3f591edad35f fwd="213.127.145.18" dyno=web.1 connect=1ms service=19788ms status=503 bytes=0
2017-01-21T15:47:11.806511+00:00 heroku[web.1]: Process exited with status 137
2017-01-21T15:47:11.823521+00:00 heroku[web.1]: State changed from up to crashed
2017-01-21T15:47:19.432716+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ticons.fokkezb.nl request_id=0a655b2b-5870-4f5d-8862-ca71dca1ee76 fwd="80.218.48.22" dyno= connect= service= status=503 bytes=
```

**Comment by FokkeZB** [comment]
It does mention something about "corrupt image", but also complains about memory. It might be a good idea to fix this as part of https://github.com/FokkeZB/TiCons-CLI/issues/53

**Comment by SPorwal** [comment]
Thanks @FokkeZB :)

**Comment by SPorwal** [comment]
For now, what do you suggest should I do? Maybe create another image if the current one is corrupted?

**Comment by FokkeZB** [comment]
I'd indeed give it another try with another image. I've tried several others and they all worked, so it seems at least in part image specific.
